### ISSUE TITLE
UnicodeDecodeError byte 0x9c

### ISSUE THREAD

**Issue by GerbenJavado** [GerbenJavado/LinkFinder#29]
Given a Burp input file the b64decode and decode('utf-8') function seem to conflict if a 0x9c byte is present. Should be fixed.

```
MBP-van-Gerben:~ gerben$ linkfinder -i desktop/htmlbundle -b -o cli

Traceback (most recent call last):
  File "/Applications/Pentesting/Linkfinder/linkfinder.py", line 208, in <module>
    urls = parser_input(args.input)  
  File "/Applications/Pentesting/Linkfinder/linkfinder.py", line 108, in parser_input
    jsfiles.append({"js":base64.b64decode(item.find('response').text).decode('utf-8'), "url":item.find('url').text})
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1741: invalid start byte
```

**Comment by GerbenJavado** [comment]
A sufficient fix could be

```
jsfiles.append({"js":base64.b64decode(item.find('response').text).decode('utf-8',"replace"), "url":item.find('url').text})
```

**Comment by GerbenJavado** [comment]
Fixed https://github.com/GerbenJavado/LinkFinder/commit/03260918e1a920a2235736cb37f12befc232ab03!
