### ISSUE TITLE
error in processing burp file

### ISSUE THREAD

**Issue by R34LUS3R** [GerbenJavado/LinkFinder#62]
LinkFile is giving me an error in processing the burp file can you please take a look at this one and help me out Thanks
```
root@user:~/tools/LinkFinder# python3 linkfinder.py -i burpfile -b
Traceback (most recent call last):
  File "linkfinder.py", line 315, in <module>
    urls = parser_input(args.input)
  File "linkfinder.py", line 92, in parser_input
    items = xml.etree.ElementTree.fromstring(open(args.input, "r").read())
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 10: invalid continuation byte
```

**Comment by realuser07** [comment]
Also I am not able to use linkfinder with only python.
```
root@root:~/tools/LinkFinder# python linkfinder.py -i burpfile -b
Traceback (most recent call last):
  File "linkfinder.py", line 315, in <module>
    urls = parser_input(args.input)
  File "linkfinder.py", line 92, in parser_input
    items = xml.etree.ElementTree.fromstring(open(args.input, "r").read())
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 2

```
