### ISSUE TITLE
What the bloody fuck?

### ISSUE THREAD

**Issue by Afaque24** [GerbenJavado/LinkFinder#65]
I am getting this bloody error 

Traceback (most recent call last):
  File "linkfinder.py", line 11, in <module>
    import re, sys, glob, html, argparse, jsbeautifier, webbrowser, subprocess, base64, ssl, xml.etree.ElementTree
ImportError: No module named html
Thats even after installing all bloody requirements!

**Comment by Afaque24** [comment]
Ok Solved by installing HTML module .

**Comment by Afaque24** [comment]
WTF?? now getting this error 
Traceback (most recent call last):
  File "linkfinder.py", line 372, in <module>
    ''' % (html.escape(url), html.escape(url))
AttributeError: 'module' object has no attribute 'escape'
